### ISSUE TITLE
Multiple environments

### ISSUE THREAD

**Issue by mreduar** [ikappas/vscode-phpcs#165]
I work with MacOS during the day and with Windows at night. I would like to have an option to configure the phpcs executable in these two environments. Because when I enter Windows for example does not work the same path as in MacOS `/usr/local/bin/phpcs`

It should be noted that I have my settings synchronized between the two machines with the [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) plugin

Any suggestions?

**Comment by dixiedream** [comment]
I have a similiar problem. I frequently switch from Win to Mac to Linux, i primarly use Docker for mu environment setup, the issue is that on Windows the extension is looking for a .bat file but the binary is compiled in a linux container. It would be nice to set the executable path with a wildcard es. /my/bin/path/phpcs.*
