### ISSUE TITLE
Ignoring files

### ISSUE THREAD

**Issue by elvishp2006** [ikappas/vscode-phpcs#22]
Has a way to configure to ignore paths and files for avoid linting?

**Comment by DaGhostman** [comment]
Would be very helpful to set a directory to lint (as that is the way the CLI works) `phpcs --standard=psr2 src/` is what I use most of the time, I don't care about the tests folder, nor any other small scripts like benchmarks or anything. So it will be super useful to have a way to whitelist/blacklist (whichever is more comfortable) some files/folders and not get the warnings from them

**Comment by elvishp2006** [comment]
Exactly, I use frameworks, and I do not want phpcs to linter from your files.

**Comment by SidIcarus** [comment]
@ikappas  
#26 appears to have no issues with the base. Is it possible to have it merged in to it?

**Comment by ikappas** [comment]
@SidIcarus I had a look at the code and looks good. But I was wondering why you feel this is a better option than setting up a ruleset.xml as so:

```xml
<?xml version="1.0"?>
<ruleset name="Project-Specific-Standard">
    <description>The coding standards used for this project.</description>
    <exclude-pattern>*/.sass-cache/*</exclude-pattern>
    <exclude-pattern>*/scripts/*</exclude-pattern>
    <exclude-pattern>*/vendor/*</exclude-pattern>
    <exclude-pattern>*/web/bin/*</exclude-pattern>
    ...
</ruleset>
```

**Comment by SidIcarus** [comment]
@ikappas 
The option makes it convenient not to have to duplicate a ruleset that is used among more then one project, custom or not, just to add one line.

In addition, you can have _always ignored_ set of directories in the ruleset and using the option allows for you ignore more if you want to focus in on certain directories / files since the inline option is appended. 

Another consideration is if the ruleset is version controlled, changing it up while you go about either of the above scenarios, you won't have to worry about committing unnecessary changes to it if others rely on it as well (including CI pulls) 

(Also, moved my comment from the PR to here since its more appropriate)

**Comment by ikappas** [comment]
@SidIcarus  I can see the utility in this... I 'll have a look over the weekend
