### ISSUE TITLE
error: "phpcs: Unexpected token S in JSON at position 0" 

### ISSUE THREAD

**Issue by LittleHamster** [ikappas/vscode-phpcs#81]
I am getting this error: 
![image](https://user-images.githubusercontent.com/10330481/34587453-69e4abbe-f176-11e7-8110-d3a6bb822d30.png)

```
phpcs --version
sh: line 1: 14805 Illegal instruction: 4  stty size 2>&1
PHP_CodeSniffer version 3.2.2 (stable) by Squiz (http://www.squiz.net)
```

I am not sure what is the problem as the error is not very descriptive, any possible solution?

**Comment by Krysio** [comment]
Probably it is a progress information log.
The extension execute phpcs command without a -q parameter - bug.

**Comment by Krysio** [comment]
[home]\.vscode\extensions\ikappas.phpcs-0.7.0\server\linter.js:221

replace
```javascript
let lintArgs = ["--report=json"];
```
to
```javascript
let lintArgs = ["-q", "--report=json"];
```

... and reload extension

**Comment by LittleHamster** [comment]
@Krysio 
I added that but still get the error

**Comment by LittleHamster** [comment]
@ikappas 
any updates about this?

**Comment by waternice** [comment]
@LittleHamster Update your php version to latest(7.1.13 || 7.2.1) once , the bug is in php not in the plugins. I have also added a pull request regarding this.

**Comment by robyngreen** [comment]
@LittleHamster I'm not sure if this is still an issue for you, as well as anyone coming here looking for advice on that same issue, that warning - for me - was because of additional output via PHP on my command line that the phpcs process was not expecting, nor should it. 

In my case my xdebug didn't match a php version, so `php -v` actually looked like this: 

`$ php -v
Xdebug requires Zend Engine API version 220131226.
The Zend Engine API version 320160303 which is installed, is newer.
Contact Derick Rethans at http://xdebug.org/docs/faq#api for a later version of Xdebug.

PHP 7.1.13 (cli) (built: Feb  2 2018 18:14:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies`

That first line "Xdebug requires Zend Engine API version 220131226." isn't typical output. It should be: 

`$ php -v
PHP 7.1.13 (cli) (built: Feb  2 2018 18:14:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies`

In your case here, the second line after `phpcs --version` is the unexpected output: 

> sh: line 1: 14805 Illegal instruction: 4  stty size 2>&1

which matches the error you see "Unexpected token S ..." That token 'S' is literally the 's' in line "sh: line 1: 14805 Illegal instruction: 4  stty size 2>&1"

You can test this by running phpcs against any file from a command line using the --report=json argument the plugin does as well: 

`$ phpcs /path/to/my/file.php --report=json`

What you should get is a raw dump of JSON on the command line. If something is injecting warnings or other text before this JSON, as can happen if a PHP extension is having problems, you'll see that string of text prior to the JSON. PHPCS doesn't know this should be there, and it really shouldn't, so it tries to start processing the JSON output from the beginning, which leads to the 'unexpected token' issues.

Figure out what is causing that line to appear in your php/phpcs output and that'll fix the issue. I also had to add the -q to lintArgs as described above.

**Comment by LittleHamster** [comment]
@robyngreen 
I am new to visual studio code and not sure how to configure the PHPCS, I used other IDEs and I could use PHPCS without issues using the same PHP version but can't get it working on VSCode
```
$ php -v
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by LittleHamster** [comment]
@ikappas 
do you think you can address this issue before version 1 release too? thanks

**Comment by ikappas** [comment]
@LittleHamster If you are referring to the -q option it has been implemented in the 1.0.0-beta.x. Please note that this option is available from PHP_CodeSniffer v.2.6.2

**Comment by rahulnever2far** [comment]
I no longer get this error. Thank you for fixing it.

**Comment by ikappas** [comment]
@rahulnever2far Nice to hear you got your issue resolved.
